[package]
name = "machine-perps"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
wide256 = []
production = ["wide256"]

[dependencies]
pinocchio = { version = "=0.11.2", default-features = false, features = ["cpi"] }
solana-address = { version = "=2.9.0", default-features = false, features = ["syscalls"] }
solana-sha256-hasher = { version = "=3.1.0", default-features = false }
pinocchio-token = "=0.7.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = true
strip = true
